N_query: 1
max_radius: 4.
field_cutoff: 2.5
std_theta_degree: 45.
std_X: 5.
# ranges: [[-21., 21.],
#          [-21., 21.],
#          [-30., -5.]]
ranges: [[-23., 23.],
         [-23., 23.],
         [-33., 0.]]
irreps_descriptor: "10x0e + 10x1e + 4x2e + 2x3e"
sh_lmax_descriptor: 3
number_of_basis_descriptor: 5
irrep_normalization: 'norm'
learnable_query: True
tp_type: 'direct'

mh_iter: 500
langevin_iter: 100

query_radius: 0.


