device: 'cuda'
characteristic_length: 0.01
plot_figsize: [28,7]
plot_result_figsize: [21,7]
pick_only: False

pick_policy: 'sorted'
pick_dist_temp: 1.
pick_policy_temp: 1.
pick_attempt_max: 100
N_transform_pick: 100
mh_iter_pick: 1000
langevin_iter_pick: 300
optim_iter_pick: 100
langevin_dt_pick: 0.001
optim_lr_pick: 0.005
X_seed_mean_pick: [0.,0., -29.]
X_seed_std_pick: [2.5, 2.5, 0.5]
max_N_query_pick: 10

place_policy: 'sorted'
place_dist_temp: 1.
place_policy_temp: 1.
place_attempt_max: 100
N_transform_place: 100
mh_iter_place: 1000
langevin_iter_place: 300
optim_iter_place: 100
langevin_dt_place: 0.001
optim_lr_place: 0.005
X_seed_mean_place: [0.,0., -29.]
X_seed_std_place: [2.5, 2.5, 0.5]
max_N_query_place: 5
query_temp_place: 1.


schedules:
  - init_seed: 100
    end_seed: 110
    mug_pose: 'arbitrary'
    mug_type: 'cups'
    distractor: True
    use_support: True
  # - init_seed: 103
  #   end_seed: 111
  #   mug_pose: 'lying'
  #   mug_type: 'cups'
  #   distractor: False
  #   use_support: True

# schedules:
#   - init_seed: 100
#     end_seed: 101
#     mug_pose: 'upright'
#     mug_type: 'cup1'
#     distractor: True
#     use_support: False
#   - init_seed: 101
#     end_seed: 102
#     mug_pose: 'upright'
#     mug_type: 'cup2'
#     distractor: True
#     use_support: False
#   - init_seed: 102
#     end_seed: 103
#     mug_pose: 'upright'
#     mug_type: 'cup3'
#     distractor: True
#     use_support: False
#   - init_seed: 103
#     end_seed: 104
#     mug_pose: 'upright'
#     mug_type: 'cup4'
#     distractor: True
#     use_support: False
#   - init_seed: 104
#     end_seed: 105
#     mug_pose: 'upright'
#     mug_type: 'cup5'
#     distractor: True
#     use_support: False
#   - init_seed: 105
#     end_seed: 106
#     mug_pose: 'upright'
#     mug_type: 'cup6'
#     distractor: True
#     use_support: False
#   - init_seed: 106
#     end_seed: 107
#     mug_pose: 'upright'
#     mug_type: 'cup7'
#     distractor: True
#     use_support: False
#   - init_seed: 107
#     end_seed: 108
#     mug_pose: 'upright'
#     mug_type: 'cup8'
#     distractor: True
#     use_support: False
#   - init_seed: 108
#     end_seed: 109
#     mug_pose: 'upright'
#     mug_type: 'cup9'
#     distractor: True
#     use_support: False
#   - init_seed: 109
#     end_seed: 110
#     mug_pose: 'upright'
#     mug_type: 'cup10'
#     distractor: True
#     use_support: False



# schedules:
#   - init_seed: 140
#     end_seed: 160
#     mug_pose: 'lying'
#     mug_type: 'cup10'
#     distractor: True
#     use_support: False

# schedules:
#   - init_seed: 100
#     end_seed: 120
#     mug_pose: 'upright'
#     mug_type: 'cup1'
#     distractor: False
#     use_support: False
#   - init_seed: 120
#     end_seed: 140
#     mug_pose: 'upright'
#     mug_type: 'cup2'
#     distractor: False
#     use_support: False
#   - init_seed: 140
#     end_seed: 160
#     mug_pose: 'upright'
#     mug_type: 'cup3'
#     distractor: False
#     use_support: False
#   - init_seed: 160
#     end_seed: 180
#     mug_pose: 'upright'
#     mug_type: 'cup4'
#     distractor: False
#     use_support: False
#   - init_seed: 180
#     end_seed: 200
#     mug_pose: 'upright'
#     mug_type: 'cup5'
#     distractor: False
#     use_support: False

